name: Wiki Sync
on:
  push:
    branches: [ main ]
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: hunam6
                access_token: ${{ secrets.WIKI }}
                commit_username: 'Hunam'
                commit_email: 'elie.tattevindrevet@gmail.com'
